/**
 * CARDIOAPI
 * Cardio API is a risk calculator API intended to help users find an estimate for their cardiovascular risk according to the 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk and the 2013 ACC/AHA Guideline on the Treatment of Blood Cholesterol to Reduce Atherosclerotic Cardiovascular Risk in Adults. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.wso2.client.api.CardioAPI;

import org.wso2.client.api.ApiException;
import org.wso2.client.model.CardioAPI.ResultIrc;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Risk of atherosclerotic cardiovascular disease.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ascvdGetTest() throws ApiException {
        Integer age = null;
        String gender = null;
        Integer systolic = null;
        String totalCholesterol = null;
        Integer hdl = null;
        Boolean diabetic = null;
        Boolean smoker = null;
        Boolean hypertensive = null;
        String race = null;
        // ResultIrc response = api.ascvdGet(age, gender, systolic, totalCholesterol, hdl, diabetic, smoker, hypertensive, race);

        // TODO: test validations
    }
    
}
