/**
 * CARDIOAPI
 * Cardio API is a risk calculator API intended to help users find an estimate for their cardiovascular risk according to the 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk and the 2013 ACC/AHA Guideline on the Treatment of Blood Cholesterol to Reduce Atherosclerotic Cardiovascular Risk in Adults. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cardioapi);
  }
}(this, function(expect, Cardioapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cardioapi.ResultIrc();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResultIrc', function() {
    it('should create an instance of ResultIrc', function() {
      // uncomment below and update the code to test ResultIrc
      //var instane = new Cardioapi.ResultIrc();
      //expect(instance).to.be.a(Cardioapi.ResultIrc);
    });

    it('should have the property computeTenYearScore (base name: "compute_ten_year_score")', function() {
      // uncomment below and update the code to test the property computeTenYearScore
      //var instane = new Cardioapi.ResultIrc();
      //expect(instance).to.be();
    });

    it('should have the property computeLifetimeRisk (base name: "compute_lifetime_risk")', function() {
      // uncomment below and update the code to test the property computeLifetimeRisk
      //var instane = new Cardioapi.ResultIrc();
      //expect(instance).to.be();
    });

    it('should have the property computeOptimalLifetime (base name: "compute_optimal_lifetime")', function() {
      // uncomment below and update the code to test the property computeOptimalLifetime
      //var instane = new Cardioapi.ResultIrc();
      //expect(instance).to.be();
    });

    it('should have the property computeTenYearRiskReduction (base name: "compute_ten_year_risk_reduction")', function() {
      // uncomment below and update the code to test the property computeTenYearRiskReduction
      //var instane = new Cardioapi.ResultIrc();
      //expect(instance).to.be();
    });

  });

}));
