/**
 * CARDIOAPI
 * Cardio API is a risk calculator API intended to help users find an estimate for their cardiovascular risk according to the 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk and the 2013 ACC/AHA Guideline on the Treatment of Blood Cholesterol to Reduce Atherosclerotic Cardiovascular Risk in Adults. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cardioapi) {
      root.Cardioapi = {};
    }
    root.Cardioapi.ResultIrc = factory(root.Cardioapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResultIrc model module.
   * @module org.wso2.client.model.CardioAPI/ResultIrc
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResultIrc</code>.
   * @alias module:org.wso2.client.model.CardioAPI/ResultIrc
   * @class
   * @param computeTenYearScore {Number} 
   * @param computeLifetimeRisk {Number} 
   * @param computeOptimalLifetime {Number} 
   * @param computeTenYearRiskReduction {Number} 
   */
  var exports = function(computeTenYearScore, computeLifetimeRisk, computeOptimalLifetime, computeTenYearRiskReduction) {
    var _this = this;

    _this['compute_ten_year_score'] = computeTenYearScore;
    _this['compute_lifetime_risk'] = computeLifetimeRisk;
    _this['compute_optimal_lifetime'] = computeOptimalLifetime;
    _this['compute_ten_year_risk_reduction'] = computeTenYearRiskReduction;
  };

  /**
   * Constructs a <code>ResultIrc</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.wso2.client.model.CardioAPI/ResultIrc} obj Optional instance to populate.
   * @return {module:org.wso2.client.model.CardioAPI/ResultIrc} The populated <code>ResultIrc</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('compute_ten_year_score')) {
        obj['compute_ten_year_score'] = ApiClient.convertToType(data['compute_ten_year_score'], 'Number');
      }
      if (data.hasOwnProperty('compute_lifetime_risk')) {
        obj['compute_lifetime_risk'] = ApiClient.convertToType(data['compute_lifetime_risk'], 'Number');
      }
      if (data.hasOwnProperty('compute_optimal_lifetime')) {
        obj['compute_optimal_lifetime'] = ApiClient.convertToType(data['compute_optimal_lifetime'], 'Number');
      }
      if (data.hasOwnProperty('compute_ten_year_risk_reduction')) {
        obj['compute_ten_year_risk_reduction'] = ApiClient.convertToType(data['compute_ten_year_risk_reduction'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} compute_ten_year_score
   */
  exports.prototype['compute_ten_year_score'] = undefined;
  /**
   * @member {Number} compute_lifetime_risk
   */
  exports.prototype['compute_lifetime_risk'] = undefined;
  /**
   * @member {Number} compute_optimal_lifetime
   */
  exports.prototype['compute_optimal_lifetime'] = undefined;
  /**
   * @member {Number} compute_ten_year_risk_reduction
   */
  exports.prototype['compute_ten_year_risk_reduction'] = undefined;



  return exports;
}));


