/*
 * CARDIOAPI
 * Cardio API is a risk calculator API intended to help users find an estimate for their cardiovascular risk according to the 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk and the 2013 ACC/AHA Guideline on the Treatment of Blood Cholesterol to Reduce Atherosclerotic Cardiovascular Risk in Adults. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.client.model.CardioAPI;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ResultIrc
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-08T12:27:20.652Z")
public class ResultIrc {
  @SerializedName("compute_ten_year_score")
  private BigDecimal computeTenYearScore = null;

  @SerializedName("compute_lifetime_risk")
  private BigDecimal computeLifetimeRisk = null;

  @SerializedName("compute_optimal_lifetime")
  private BigDecimal computeOptimalLifetime = null;

  @SerializedName("compute_ten_year_risk_reduction")
  private BigDecimal computeTenYearRiskReduction = null;

  public ResultIrc computeTenYearScore(BigDecimal computeTenYearScore) {
    this.computeTenYearScore = computeTenYearScore;
    return this;
  }

   /**
   * Get computeTenYearScore
   * @return computeTenYearScore
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getComputeTenYearScore() {
    return computeTenYearScore;
  }

  public void setComputeTenYearScore(BigDecimal computeTenYearScore) {
    this.computeTenYearScore = computeTenYearScore;
  }

  public ResultIrc computeLifetimeRisk(BigDecimal computeLifetimeRisk) {
    this.computeLifetimeRisk = computeLifetimeRisk;
    return this;
  }

   /**
   * Get computeLifetimeRisk
   * @return computeLifetimeRisk
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getComputeLifetimeRisk() {
    return computeLifetimeRisk;
  }

  public void setComputeLifetimeRisk(BigDecimal computeLifetimeRisk) {
    this.computeLifetimeRisk = computeLifetimeRisk;
  }

  public ResultIrc computeOptimalLifetime(BigDecimal computeOptimalLifetime) {
    this.computeOptimalLifetime = computeOptimalLifetime;
    return this;
  }

   /**
   * Get computeOptimalLifetime
   * @return computeOptimalLifetime
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getComputeOptimalLifetime() {
    return computeOptimalLifetime;
  }

  public void setComputeOptimalLifetime(BigDecimal computeOptimalLifetime) {
    this.computeOptimalLifetime = computeOptimalLifetime;
  }

  public ResultIrc computeTenYearRiskReduction(BigDecimal computeTenYearRiskReduction) {
    this.computeTenYearRiskReduction = computeTenYearRiskReduction;
    return this;
  }

   /**
   * Get computeTenYearRiskReduction
   * @return computeTenYearRiskReduction
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getComputeTenYearRiskReduction() {
    return computeTenYearRiskReduction;
  }

  public void setComputeTenYearRiskReduction(BigDecimal computeTenYearRiskReduction) {
    this.computeTenYearRiskReduction = computeTenYearRiskReduction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultIrc resultIrc = (ResultIrc) o;
    return Objects.equals(this.computeTenYearScore, resultIrc.computeTenYearScore) &&
        Objects.equals(this.computeLifetimeRisk, resultIrc.computeLifetimeRisk) &&
        Objects.equals(this.computeOptimalLifetime, resultIrc.computeOptimalLifetime) &&
        Objects.equals(this.computeTenYearRiskReduction, resultIrc.computeTenYearRiskReduction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(computeTenYearScore, computeLifetimeRisk, computeOptimalLifetime, computeTenYearRiskReduction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultIrc {\n");
    
    sb.append("    computeTenYearScore: ").append(toIndentedString(computeTenYearScore)).append("\n");
    sb.append("    computeLifetimeRisk: ").append(toIndentedString(computeLifetimeRisk)).append("\n");
    sb.append("    computeOptimalLifetime: ").append(toIndentedString(computeOptimalLifetime)).append("\n");
    sb.append("    computeTenYearRiskReduction: ").append(toIndentedString(computeTenYearRiskReduction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

