/**
 * CARDIOAPI
 * Cardio API is a risk calculator API intended to help users find an estimate for their cardiovascular risk according to the 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk and the 2013 ACC/AHA Guideline on the Treatment of Blood Cholesterol to Reduce Atherosclerotic Cardiovascular Risk in Adults. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'org.wso2.client.model.CardioAPI/ResultIrc', 'org.wso2.client.api.CardioAPI/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./org.wso2.client.model.CardioAPI/ResultIrc'), require('./org.wso2.client.api.CardioAPI/DefaultApi'));
  }
}(function(ApiClient, ResultIrc, DefaultApi) {
  'use strict';

  /**
   * Cardio_API_is_a_risk_calculator_API_intended_to_help_users_find_an_estimate_for_their_cardiovascular_risk_according_to_the_2013_ACCAHA_Guideline_on_the_Assessment_of_Cardiovascular_Risk_and_the_2013_ACCAHA_Guideline_on_the_Treatment_of_Blood_Cholesterol_to_Reduce_Atherosclerotic_Cardiovascular_Risk_in_Adults_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Cardioapi = require('index'); // See note below*.
   * var xxxSvc = new Cardioapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Cardioapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Cardioapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Cardioapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ResultIrc model constructor.
     * @property {module:org.wso2.client.model.CardioAPI/ResultIrc}
     */
    ResultIrc: ResultIrc,
    /**
     * The DefaultApi service constructor.
     * @property {module:org.wso2.client.api.CardioAPI/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
